_include_models:
- models/llama3_aloe_8b_alpha.yaml
- models/llama3_aloe_8b_alpha.yaml
- models/llama3_aloe_8b_alpha.yaml
- models/llama3_aloe_8b_alpha.yaml
- models/llama3_aloe_8b_alpha.yaml
- models/llama3_aloe_8b_alpha.yaml
- models/llama3_aloe_8b_alpha.yaml
- models/llama3_aloe_8b_alpha.yaml
- models/llama3_aloe_8b_alpha.yaml
- models/llama3_aloe_8b_alpha.yaml
- models/llama3_aloe_8b_alpha.yaml
- models/llama3_aloe_8b_alpha.yaml
calibrated: false
_include_calibration: calibration/adaptive_temperature_pubmedqa_1000samples.yaml
wagering_method:
  name: centralized_wagers
  config:
    hidden_dim: 4096
    hidden_layers:
    - 512
    - 256
    hidden_state_layers_per_model:
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    learning_rate: 5e-6
    temperature: 2.0
    grad_clip_norm: 1.0
    normalize_hidden_states: false
    device: cuda:0
aggregation:
  name: linear_pooling
  config: {}
option_tokens:
- 'YES'
- 'NO'
cache_path: /research/projects/ecoai/yl2310/MultiLLMs/cache
_include_datasets:
- datasets/pubmedqa_context_only.yaml
num_epochs: 50
checkpoint_base_dir: /research/projects/ecoai/yl2310/MultiLLMs/checkpoints
training_batch_size: 100
auto_resume: false
balance_training_datasets: true
shuffle_data: true
shuffle_seed: 18
early_stopping_patience: 5
early_stopping_criterion: validation
report_to_wandb: false
wandb_project: multi-llm-wagering
wandb_entity: null
wandb_name: centralized_wagers_pubmedqa_mixed_layers_12
_include_test_datasets:
- datasets/pubmedqa_context_only.yaml
test_datasets:
- display_name: pubmedqa_test
