_include_models:
- models/gemma_2_9b_it.yaml
- models/gemma_2_9b_it.yaml
- models/gemma_2_9b_it.yaml
- models/gemma_2_9b_it.yaml
- models/gemma_2_9b_it.yaml
- models/gemma_2_9b_it.yaml
- models/gemma_2_9b_it.yaml
- models/gemma_2_9b_it.yaml
- models/gemma_2_9b_it.yaml
- models/gemma_2_9b_it.yaml
- models/gemma_2_9b_it.yaml
- models/gemma_2_9b_it.yaml
checkpoint_base_dir: /research/projects/ecoai/yl2310/WALLA/checkpoints
checkpoint_path: /research/projects/ecoai/yl2310/WALLA/checkpoints/dummy_kl_uniform_wagers
cache_path: /research/projects/ecoai/yl2310/WALLA/cache
calibrated: false
shuffle_data: true
shuffle_seed: 18
wagering_method:
  name: kl_uniform_wagers
  config:
    confidence_epsilon: 1.0e-08
aggregation:
  name: linear_pooling
  config: {}
report_to_wandb: false
wandb_project: multi-llm-wagering
wandb_entity: null
wandb_name: kl_uniform_wagers_cluster_saturation_bayesX_mixed_layers_eval
option_tokens:
- '1'
- '0'
included_test_dataset: datasets/cluster_saturation_bayesX.yaml
