_include_models:
- models/llama3_aloe_8b_alpha.yaml
- models/llama3_aloe_8b_alpha.yaml
- models/llama3_aloe_8b_alpha.yaml
- models/llama3_aloe_8b_alpha.yaml
- models/llama3_aloe_8b_alpha.yaml
- models/llama3_aloe_8b_alpha.yaml
- models/llama3_aloe_8b_alpha.yaml
- models/llama3_aloe_8b_alpha.yaml
- models/llama3_aloe_8b_alpha.yaml
- models/llama3_aloe_8b_alpha.yaml
- models/llama3_aloe_8b_alpha.yaml
- models/llama3_aloe_8b_alpha.yaml
checkpoint_path: /research/projects/ecoai/yl2310/MultiLLMs/checkpoints/dummy_kl_uniform_wagers
calibrated: false
_include_calibration: calibration/adaptive_temperature_pubmedqa_1000samples.yaml
shuffle_data: true
shuffle_seed: 18
wagering_method:
  name: kl_uniform_wagers
  config:
    confidence_epsilon: 1.0e-08
aggregation:
  name: linear_pooling
  config: {}
report_to_wandb: false
wandb_project: multi-llm-wagering
wandb_entity: null
wandb_name: kl_uniform_wagers_pubmedqa_eval
_include_test_datasets:
- datasets/pubmedqa_context_only.yaml
test_datasets:
- display_name: pubmedqa_test
option_tokens:
- 'YES'
- 'NO'
cache_path: /research/projects/ecoai/yl2310/MultiLLMs/cache
