_include_models:
- models/llama3_aloe_8b_alpha.yaml
- models/llama3_1_8b_instruct.yaml
checkpoint_path: /research/projects/ecoai/yl2310/MultiLLMs/checkpoints/dummy_kl_uniform_wagers
calibrated: false
_include_calibration: calibration/adaptive_temperature_1000samples.yaml
shuffle_data: true
shuffle_seed: 18
wagering_method:
  name: kl_uniform_wagers
  config:
    confidence_epsilon: 1.0e-08
aggregation:
  name: linear_pooling
  config: {}
option_tokens:
- A
- B
- C
- D
report_to_wandb: true
wandb_project: multi-llm-wagering
wandb_entity: null
wandb_name: kl_uniform_wagers_mixed_data_4_eval
_include_test_datasets:
- datasets/mmlu_full.yaml
- datasets/medmcqa.yaml
shared_source_tripartition: true
test_datasets:
- display_name: mmlu_full_test
  eval_split: auxiliary_train
- display_name: medmcqa_test
  eval_split: train
_include_ood_datasets:
- datasets/arc_challenge.yaml
- datasets/forecastqa.yaml
ood_datasets:
- display_name: arc_challenge_ood
  eval_split: test
- display_name: forecastqa_ood
  eval_split: train
