_include_models:
- models/gemma_2_9b_it.yaml
- models/gemma_2_9b_it.yaml
- models/gemma_2_9b_it.yaml
- models/gemma_2_9b_it.yaml
calibrated: false
cache_path: /research/projects/ecoai/yl2310/MultiLLMs/cache
wagering_method:
  name: mse_br_wagers_v3
  config:
    hidden_layers:
    - 512
    - 256
    hidden_state_layers_per_model:
    - -4
    - -3
    - -2
    - -1
    learning_rate: 5e-6
    lr_decay_factor: 1
    lr_decay_steps: 100
    temperature: 2.0
    grad_clip_norm: 1.0
    normalize_hidden_states: false
    device: cuda:0
    common_hidden_dim: 4096
aggregation:
  name: linear_pooling
  config: {}
option_tokens:
- '1'
- '0'
_include_datasets:
- datasets/cluster_saturation_bayesX.yaml
num_epochs: 5
checkpoint_base_dir: /research/projects/ecoai/yl2310/MultiLLMs/checkpoints
training_batch_size: 100
auto_resume: false
balance_training_datasets: true
shuffle_data: true
shuffle_seed: 18
early_stopping_patience: 1500
early_stopping_criterion: online_learning
use_min_kl_for_early_stopping: true
report_to_wandb: true
wandb_project: multi-llm-wagering
wandb_entity: null
wandb_name: mse_br_wagers_v3_cluster_saturation_bayesX_mixed_layers_4
_include_test_datasets:
- datasets/cluster_saturation_bayesX.yaml
