_include_models:
- models/gemma_2_9b_it.yaml
- models/llama3_aloe_8b_alpha.yaml
- models/llama3_1_8b_instruct.yaml
- models/biomistral_7b.yaml
- models/gemma_2_9b_it.yaml
- models/llama3_aloe_8b_alpha.yaml
- models/llama3_1_8b_instruct.yaml
- models/biomistral_7b.yaml
checkpoint_path: /common/users/yl2310/MultiLLMs/checkpoints/dummy_packllm_perplexity_wagers
calibrated: false
_include_calibration: calibration/adaptive_temperature_1000samples.yaml
cache_path: /common/users/yl2310/MultiLLMs/cache
shuffle_data: true
shuffle_seed: 18
wagering_method:
  name: packllm_perplexity_wagers
  config:
    tau: 1.0
    epsilon: 1.0e-12
aggregation:
  name: linear_pooling
  config: {}
report_to_wandb: true
wandb_project: multi-llm-wagering
wandb_entity: null
wandb_name: packllm_perplexity_wagers_eval_8models
_include_test_datasets:
- datasets/mmlu_full.yaml
- datasets/medmcqa.yaml
test_datasets:
- display_name: mmlu_full_test
  eval_split: test
- display_name: medmcqa_test
  eval_split: validation
_include_ood_dataset: datasets/arc_challenge.yaml
ood_dataset:
  display_name: arc_challenge_ood
  eval_split: test
option_tokens:
- A
- B
- C
- D
