_include_models:
- models/gemma_2_9b_it.yaml
- models/llama3_1_8b_instruct.yaml
- models/llama3_aloe_8b_alpha.yaml
- models/biomistral_7b.yaml
checkpoint_base_dir: /research/projects/ecoai/yl2310/WALLA/checkpoints
checkpoint_path: /research/projects/ecoai/yl2310/WALLA/checkpoints/dummy_packllm_perplexity_wagers
calibrated: false
shuffle_data: true
shuffle_seed: 18
wagering_method:
  name: packllm_perplexity_wagers
  config:
    tau: 1.0
    epsilon: 1.0e-12
aggregation:
  name: linear_pooling
  config: {}
option_tokens:
- 'YES'
- 'NO'
cache_path: /research/projects/ecoai/yl2310/WALLA/cache
report_to_wandb: false
wandb_project: multi-llm-wagering
wandb_entity: null
wandb_name: packllm_perplexity_wagers_hetero_4models_pubmedqa_wrong_context
included_test_dataset: datasets/pubmedqa_context_only_wrong_context.yaml
test_dataset:
  display_name: pubmedqa_test
