_include_models:
- models/gemma_2_9b_it.yaml
- models/gemma_2_9b_it.yaml
- models/gemma_2_9b_it.yaml
- models/gemma_2_9b_it.yaml
- models/gemma_2_9b_it.yaml
- models/gemma_2_9b_it.yaml
- models/gemma_2_9b_it.yaml
- models/gemma_2_9b_it.yaml
- models/gemma_2_9b_it.yaml
- models/gemma_2_9b_it.yaml
- models/gemma_2_9b_it.yaml
- models/gemma_2_9b_it.yaml
checkpoint_path: /common/users/yl2310/MultiLLMs/checkpoints/dummy_packllm_perplexity_wagers
cache_path: /research/projects/ecoai/yl2310/MultiLLMs/cache
calibrated: false
shuffle_data: true
shuffle_seed: 18
wagering_method:
  name: packllm_perplexity_wagers
  config:
aggregation:
  name: linear_pooling
  config: {}
_include_test_datasets:
- datasets/cluster_saturation_bayesX.yaml
option_tokens:
- '1'
- '0'
report_to_wandb: false
wandb_project: multi-llm-wagering
wandb_entity: null
wandb_name: packllm_perplexity_wagers_cluster_saturation_bayesX_mixed_layers_eval_12
