_include_models:
- models/gemma_2_9b_it.yaml
- models/llama3_1_8b_instruct.yaml
- models/llama3_aloe_8b_alpha.yaml
- models/biomistral_7b.yaml
calibrated: false
_include_calibration: calibration/adaptive_temperature_pubmedqa_1000samples.yaml
wagering_method:
  name: router_dc
  config:
    encoder_model_name: microsoft/mdeberta-v3-base
    debug_param_dtypes: true
    tokenizer_use_fast: false
    max_seq_length: 512
    learning_rate: 1e-6
    lr_decay_factor: 1
    lr_decay_steps: 100
    temperature: 1.0
    encoder_lr_mult: 0.01
    grad_clip_norm: 0.5
    max_grad_norm_before_skip: 1000
    weight_decay: 0.01
    freeze_encoder: false
    pubmedqa_strip_context: true
    similarity_function: cos
    top_k: 3
    last_k: 3
    min_pos_p: 0.01
    neg_mask_threshold: 0.5
    device: cuda:0
aggregation:
  name: linear_pooling
  config: {}
option_tokens:
- 'YES'
- 'NO'
cache_path: /research/projects/ecoai/yl2310/MultiLLMs/cache
_include_datasets:
- datasets/pubmedqa_context_only_wrong_context.yaml
num_epochs: 5
checkpoint_base_dir: /research/projects/ecoai/yl2310/MultiLLMs/checkpoints
training_batch_size: 50
wager_score_plot_every: 200
auto_resume: false
balance_training_datasets: true
shuffle_data: true
shuffle_seed: 18
early_stopping_patience: 5
early_stopping_criterion: validation
report_to_wandb: false
wandb_project: multi-llm-wagering
wandb_entity: null
wandb_name: router_dc_hetero_4models_pubmedqa_wrong_context
shared_source_tripartition: true
_include_test_datasets:
- datasets/pubmedqa_context_only_wrong_context.yaml
test_datasets:
- display_name: pubmedqa_test
