_include_models:
- models/llama3_aloe_8b_alpha.yaml
- models/llama3_aloe_8b_alpha.yaml
- models/llama3_aloe_8b_alpha.yaml
- models/llama3_aloe_8b_alpha.yaml
- models/llama3_aloe_8b_alpha.yaml
- models/llama3_aloe_8b_alpha.yaml
- models/llama3_aloe_8b_alpha.yaml
- models/llama3_aloe_8b_alpha.yaml
calibrated: false
wagering_method:
  name: stacked_generalization
  config:
    hidden_dim: 4096
    hidden_layers:
    - 512
    - 256
    learning_rate: 5e-6
    temperature: 2.0
    grad_clip_norm: 1.0
    normalize_hidden_states: false
    device: cuda:0
aggregation:
  name: linear_pooling
  config: {}
option_tokens:
- 'YES'
- 'NO'
cache_path: /research/projects/ecoai/yl2310/WALLA/cache
num_epochs: 50
checkpoint_base_dir: /research/projects/ecoai/yl2310/WALLA/checkpoints
training_batch_size: 100
shuffle_data: true
shuffle_seed: 18
early_stopping_patience: 5
early_stopping_criterion: validation
report_to_wandb: false
wandb_project: multi-llm-wagering
wandb_entity: null
wandb_name: stacked_generalization_pubmedqa_mixed_layers_8
included_dataset: datasets/pubmedqa_context_only.yaml
included_test_dataset: datasets/pubmedqa_context_only.yaml
test_dataset:
  display_name: pubmedqa_test
