# Biomistral-7B model configuration
path: BioMistral/BioMistral-7B
path_to_load_script: model/default_causal.py
type: CausalLM
instruct: false
load_model_args:
  device_map: auto
load_tokenizer_args: {}

