name:
- allenai/ai2_arc
- ARC-Challenge
display_name: arc_challenge
text_column: question
label_column: answerKey
batch_size: 8
trust_remote_code: false
prompt: 'Return the label of the correct answer for the question below.


  Question: {question}

  Choices:

  {choices}

  Answer:'
description: ''
