name: openlifescienceai/medmcqa
display_name: medmcqa
text_column: question
label_column: cop
batch_size: 5
trust_remote_code: false
prompt: 'Return the label of the correct answer for the question below.


  Question: {question}

  Choices:

  {choices}

  Answer:'
description: ''
partition:
  mode: uniform
  ratios:
  - 0.8
  - 0.1
  - 0.1

