name: qiaojin/PubMedQA
train_config_name: pqa_artificial
eval_config_name: pqa_artificial
display_name: pubmedqa_context_only
text_column: question
label_column: final_decision
batch_size: 5
trust_remote_code: false
prompt: 'Question:

  {question}

  You are an expert in medical science and you have classified access to the following
  context.

  Context:

  {context}

  Answer with YES or NO. Answer:'
prompt_without_context: 'Question:

  {question}

  Answer with YES or NO. Answer:'
description: ''
pubmedqa_wrong_context_routing: true
pubmedqa_split_ratios:
- 0.8
- 0.1
- 0.1
